### ISSUE TITLE
Lockbox does not preserve search path load order

### ISSUE THREAD

**Issue by robertzk** [robertzk/lockbox#79]
If we have 

``` yml
   -
     name: mungebits
     version: 0.3.13
     repo: robertzk/mungebits
   -
     name: mungebits2
     version: 0.1.0.9003
     repo: syberia/mungebits2
```

instead of

``` yml
   -
     name: mungebits2
     version: 0.1.0.9003
     repo: syberia/mungebits2
   -
     name: mungebits
     version: 0.3.13
     repo: robertzk/mungebits
```

it may be critical that mungebits is loaded _first_ so that mungebits2 takes priority in the `search()` order. This is necessary if one packages shadows the other and we wish to prefer one package's functions over another (dplyr and plyr have the same conflicts).
